---
abstract: 'Implements the Null Class design pattern'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100960'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Null
provides:
  Class::Null:
    file: lib/Class/Null.pm
    version: 2.101420
recommends: {}
requires:
  overload: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Class-Null
  homepage: http://search.cpan.org/dist/Class-Null/
  repository: http://github.com/hanekomu/Class-Null
version: 2.101420
