---
name: Class-Null
version: 1.04
author:
  - Marcel Gruenauer <marcel@noug.at>
abstract: Implements the Null Class design pattern
license: perl
build_requires:
  Test::Pod: 1.20
  Test::Pod::Coverage: 1.06
provides:
  Class::Null:
    file: lib/Class/Null.pm
    version: 1.04
generated_by: Module::Build version 0.2611
